tools: created credentials.py
socallinuxexpo/scale-av-cutter pull request #25
Opened 2023-12-18 21:29 UTC by destevae

Addresses the authentication enhancement mentioned [here](https://github.com/socallinuxexpo/scale-av-cutter/issues/24).
Created a new credentials.py file to allow for separate initial authentication for Youtube uploads. To run credentials.py, execute `./credentials.py -c client_secrets.json`, where client_secrets.json is the file from the Google API Client.

Made some other changes so the flask app and scripts could run.
1. Added `app.app_context().push()` in main.py and changed `flow.run_console()` to `flow.run_local_server(bind_addr="0.0.0.0", open_browser=False, port=10000)`.
2. In signxml.py, instead of importing Markup from flask, changed to importing Markup from markupsafe.

2023-12-20 08:15 UTC, EaterOA requested changes

2023-12-20 08:15 UTC, EaterOA commented on tools/credentials.py
> +    flow.run_local_server(bind_addr="0.0.0.0", open_browser=False, port=10000)
FWIW not setting `bind_addr` and letting it be localhost seems to work too, if the browser is local of course (e.g. a laptop or desktop). Opening it to 0.0.0.0 is the most flexible, at the cost of temporarily exposing an easily guessable port, though I don't really have strong opinions here. Just a heads-up to @ldang that this is the behavior.

2023-12-20 08:15 UTC, EaterOA commented on tools/credentials.py
> +    if os.path.isfile(args.token):
If you put everything from here down to `json.dump` to a separate function, then `upload.py` can reuse it wholesale. Currently this part is exactly the same.

2023-12-20 17:15 UTC, destevae commented on main.py
> +app.app_context().push()
Yes, the issue occurred on the `db.create_all()` line in main.py and was `RuntimeError: Working outside of application context. This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.`

2023-12-20 17:15 UTC, destevae commented on tools/split.py
> +from unidecode import unidecode
Yep, I've added it to `requirements.txt` in my newest commit.

2023-12-20 17:16 UTC, destevae commented on tools/split.py
> +    s = unidecode(s)
No, it was added to solve a small special character bug mentioned in issue #8

2023-12-21 07:03 UTC, EaterOA commented on tools/split.py
> +    s = unidecode(s)
Copy. Interesting library.

2023-12-21 07:06 UTC, EaterOA approved these changes

2023-12-21 15:51 UTC, merged